//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusyDiesel_
    {
        public double PK_busyDB { get; set; }
        public string DATE_IN { get; set; }
        public string TIME_IN { get; set; }
        public string CUR_IN_BUSY { get; set; }
    }
}
