//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Bay_Station__
    {
        public double Bay_Station_ID { get; set; }
        public Nullable<double> PO_Number { get; set; }
        public Nullable<System.DateTime> Date_to_Order { get; set; }
        public Nullable<System.DateTime> Time_to_Order { get; set; }
        public string Vehicle_Number { get; set; }
        public Nullable<System.DateTime> Fill_Start_Time { get; set; }
        public Nullable<System.DateTime> Fill_End_Time { get; set; }
        public Nullable<double> Filling_Time_diesel_ { get; set; }
        public Nullable<double> Filling_Time_gasohol95_ { get; set; }
        public Nullable<double> Employee_ID { get; set; }
    }
}
