//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Inventory_Stock_Card__
    {
        public string Patrol_Type { get; set; }
        public Nullable<double> Beginning_Stock { get; set; }
        public Nullable<double> Purchased { get; set; }
        public Nullable<double> Sold { get; set; }
        public Nullable<double> Ending_Stock { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string F12 { get; set; }
        public string F13 { get; set; }
        public string F14 { get; set; }
        public string F15 { get; set; }
        public string F16 { get; set; }
        public string F17 { get; set; }
        public string F18 { get; set; }
        public string F19 { get; set; }
        public string F20 { get; set; }
        public string F21 { get; set; }
        public string F22 { get; set; }
        public string F23 { get; set; }
        public string F24 { get; set; }
        public string F25 { get; set; }
        public string F26 { get; set; }
        public string F27 { get; set; }
        public string F28 { get; set; }
        public string F29 { get; set; }
        public string F30 { get; set; }
        public string F31 { get; set; }
        public string F32 { get; set; }
        public string F33 { get; set; }
        public string F34 { get; set; }
        public string F35 { get; set; }
        public string F36 { get; set; }
        public string F37 { get; set; }
        public string F38 { get; set; }
        public string F39 { get; set; }
        public string F40 { get; set; }
        public string F41 { get; set; }
        public string F42 { get; set; }
        public string F43 { get; set; }
        public string F44 { get; set; }
        public string F45 { get; set; }
        public string F46 { get; set; }
        public string F47 { get; set; }
        public string F48 { get; set; }
        public string F49 { get; set; }
        public string F50 { get; set; }
        public string F51 { get; set; }
        public string F52 { get; set; }
        public string F53 { get; set; }
        public string F54 { get; set; }
        public string F55 { get; set; }
        public string F56 { get; set; }
        public string F57 { get; set; }
    }
}
