//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Monthly_Income_Statement__
    {
        public string Type { get; set; }
        public Nullable<double> Sale { get; set; }
        public Nullable<double> Cost_of_good_sold { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
        public string F6 { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
    }
}
