//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Sale_Office__
    {
        public double PO_Number { get; set; }
        public Nullable<double> Bay_Station_ID { get; set; }
        public Nullable<double> CustomerAddress { get; set; }
        public Nullable<double> Customer_ID { get; set; }
        public Nullable<double> PaymentID { get; set; }
        public Nullable<System.DateTime> Date_to_Order { get; set; }
        public string Gas_Type { get; set; }
        public Nullable<double> LITRE { get; set; }
        public Nullable<double> Price_Baht___Liter_of_each_day { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<System.DateTime> Time_to_Order { get; set; }
        public Nullable<double> Employee_ID { get; set; }
        public string Vehicle_Number { get; set; }
    }
}
