//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SE_Diesel_Bay__
    {
        public double PK_SEDB { get; set; }
        public string Date { get; set; }
        public string PO_NUMBER { get; set; }
        public string TIME_IN { get; set; }
        public string TIME_OUT { get; set; }
        public Nullable<System.DateTime> F6 { get; set; }
    }
}
