//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Total_Calculate___
    {
        public double Total_SALE { get; set; }
        public Nullable<double> Total_COGS { get; set; }
        public Nullable<double> Gross_profit_ { get; set; }
        public Nullable<double> Sale_office_station { get; set; }
        public Nullable<double> Gate_Controller { get; set; }
        public Nullable<double> Utility_Expense { get; set; }
        public Nullable<double> Depreciation { get; set; }
        public Nullable<double> Net_Income { get; set; }
    }
}
