//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Capstone2Entities9 : DbContext
    {
        public Capstone2Entities9()
            : base("name=Capstone2Entities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Bay_Station__> C_Bay_Station__ { get; set; }
        public virtual DbSet<BusyDiesel_> BusyDiesel_ { get; set; }
        public virtual DbSet<BusyExitGate_> BusyExitGate_ { get; set; }
        public virtual DbSet<BusyGasohol95_> BusyGasohol95_ { get; set; }
        public virtual DbSet<BusyInboundWB_> BusyInboundWB_ { get; set; }
        public virtual DbSet<BusyOutboundWB_> BusyOutboundWB_ { get; set; }
        public virtual DbSet<BusySalesOffice_> BusySalesOffice_ { get; set; }
        public virtual DbSet<Customer_> Customer_ { get; set; }
        public virtual DbSet<Employee_> Employee_ { get; set; }
        public virtual DbSet<GLAccountPayable_> GLAccountPayable_ { get; set; }
        public virtual DbSet<GLAccountRecievable_> GLAccountRecievable_ { get; set; }
        public virtual DbSet<GLCash_> GLCash_ { get; set; }
        public virtual DbSet<GLDiesel_> GLDiesel_ { get; set; }
        public virtual DbSet<GLGasohol95_> GLGasohol95_ { get; set; }
        public virtual DbSet<C_Inventory_Stock_Card__> C_Inventory_Stock_Card__ { get; set; }
        public virtual DbSet<Invoice_> Invoice_ { get; set; }
        public virtual DbSet<C_Journalize___> C_Journalize___ { get; set; }
        public virtual DbSet<C_Monthly_Income_Statement__> C_Monthly_Income_Statement__ { get; set; }
        public virtual DbSet<Payment_> Payment_ { get; set; }
        public virtual DbSet<Purchase_> Purchase_ { get; set; }
        public virtual DbSet<Reconciliation_> Reconciliation_ { get; set; }
        public virtual DbSet<C_Sale_Office__> C_Sale_Office__ { get; set; }
        public virtual DbSet<C_SE_Diesel_Bay__> C_SE_Diesel_Bay__ { get; set; }
        public virtual DbSet<SE_Gasohol95_> SE_Gasohol95_ { get; set; }
        public virtual DbSet<SE_InboundWB_> SE_InboundWB_ { get; set; }
        public virtual DbSet<SE_OutboundWB_> SE_OutboundWB_ { get; set; }
        public virtual DbSet<SE_SaleOffice_> SE_SaleOffice_ { get; set; }
        public virtual DbSet<C_Total_Calculate___> C_Total_Calculate___ { get; set; }
        public virtual DbSet<Transaction_> Transaction_ { get; set; }
        public virtual DbSet<Transaction2_> Transaction2_ { get; set; }
        public virtual DbSet<Truck_> Truck_ { get; set; }
    }
}
