//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_
    {
        public double Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Surname { get; set; }
        public string Employee_Phonenumber { get; set; }
        public string E_mail { get; set; }
        public string Employee_Position { get; set; }
        public Nullable<System.DateTime> Date_of_Birthday { get; set; }
        public Nullable<double> Age { get; set; }
        public string Gender { get; set; }
        public string Password { get; set; }
    }
}
