//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLDiesel_
    {
        public double PK_diesel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Explaination { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Crredit { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
