//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_
    {
        public double Invoice_No_ { get; set; }
        public string Company_Name { get; set; }
        public string Address { get; set; }
        public Nullable<double> PO_Number { get; set; }
        public Nullable<double> Payment_No_ { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> CustomerAddress { get; set; }
        public Nullable<double> Customer_ID { get; set; }
        public string Customer { get; set; }
        public Nullable<double> Tax_Payer_ID { get; set; }
        public Nullable<double> Bay_Station_ID { get; set; }
        public Nullable<double> Filling_Time { get; set; }
        public string Vehicle_Number { get; set; }
        public string Item { get; set; }
        public Nullable<double> Q_ty { get; set; }
        public Nullable<double> Price_Liter { get; set; }
        public Nullable<double> AMOUNT_Bath_ { get; set; }
        public Nullable<double> Vat_7___inclusive_ { get; set; }
        public Nullable<double> Grand_Total { get; set; }
    }
}
