//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_
    {
        public double Payment_No_ { get; set; }
        public Nullable<double> CustomerAddress { get; set; }
        public Nullable<double> Customer_ID { get; set; }
        public Nullable<double> PO_Number { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> Datepaid { get; set; }
        public Nullable<System.DateTime> Timepaid { get; set; }
        public Nullable<double> Employee_ID { get; set; }
        public string Vehicle_Number { get; set; }
    }
}
