//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconciliation_
    {
        public double Shipment_No_ { get; set; }
        public Nullable<double> Payment_No_ { get; set; }
        public Nullable<double> PO_Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Invioce_No_ { get; set; }
        public string VEHICLE_NUMBER { get; set; }
        public string Partol_Type { get; set; }
        public Nullable<double> Q_ty__Liter_ { get; set; }
        public Nullable<double> AMOUNT_Bath_ { get; set; }
        public string Agent { get; set; }
    }
}
