//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_
    {
        public double Transaction_ID { get; set; }
        public Nullable<System.DateTime> Sort_Date { get; set; }
        public Nullable<double> Amount_Filling_Time_diesel_ { get; set; }
        public Nullable<double> Amount_Filling_Time_gasohol95_ { get; set; }
        public Nullable<double> Amount_of_Fuel_diesel_ { get; set; }
        public Nullable<double> Amount_of_Fuel_gasohol95_ { get; set; }
        public Nullable<double> C_Truck_In { get; set; }
        public Nullable<double> Truck_Out { get; set; }
    }
}
