//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationBackEnd.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck_
    {
        public string Vehicle_Number { get; set; }
        public Nullable<double> Driver_ID { get; set; }
        public string Driver_Name { get; set; }
        public string Driver_Surname { get; set; }
        public string Driver_Phonenumber { get; set; }
    }
}
